{
	"name": "CVE-2009-5010",
	"seq": "2009-5010",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20101019"
	},
	"desc": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.1 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, a different vulnerability than CVE-2010-3494.",
	"refs": [
		{
			"text": "http://code.google.com/p/pyftpdlib/issues/detail?id=91",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=91"
		},
		{
			"text": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
		},
		{
			"text": "http://code.google.com/p/pyftpdlib/source/detail?r=439",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/source/detail?r=439"
		},
		{
			"text": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&r=439&format=side&path=/trunk/pyftpdlib/ftpserver.py",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn439&amp;r=439&amp;format=side&amp;path=/trunk/pyftpdlib/ftpserver.py"
		},
		{
			"text": "http://bugs.python.org/issue6706",
			"source": "MISC",
			"url": "http://bugs.python.org/issue6706"
		},
		{
			"text": "https://bugs.launchpad.net/zodb/+bug/135108",
			"source": "MISC",
			"url": "https://bugs.launchpad.net/zodb/+bug/135108"
		},
		{
			"text": "[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
		},
		{
			"text": "[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
		},
		{
			"text": "[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
		},
		{
			"text": "[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases",
			"source": "MLIST",
			"url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
		}
	],
	"votes": {}
}
