{
	"name": "CVE-2009-5011",
	"seq": "2009-5011",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20101019"
	},
	"desc": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
	"refs": [
		{
			"text": "http://code.google.com/p/pyftpdlib/issues/detail?id=100",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/issues/detail?id=100"
		},
		{
			"text": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
		},
		{
			"text": "http://code.google.com/p/pyftpdlib/source/detail?r=543",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/source/detail?r=543"
		},
		{
			"text": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py",
			"source": "CONFIRM",
			"url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&amp;r=543&amp;format=side&amp;path=/trunk/pyftpdlib/ftpserver.py"
		}
	],
	"votes": {}
}
