{
	"name": "CVE-2024-3657",
	"seq": "2024-3657",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20240411"
	},
	"desc": "A flaw was found in 389-ds-base. A specially-crafted LDAP query can potentially cause a failure on the directory server, leading to a denial of service",
	"refs": [
		{
			"text": "https://bugzilla.redhat.com/show_bug.cgi?id=2274401",
			"source": "MISC",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274401"
		},
		{
			"text": "https://access.redhat.com/errata/RHSA-2024:3591",
			"source": "MISC",
			"url": "https://access.redhat.com/errata/RHSA-2024:3591"
		},
		{
			"text": "https://access.redhat.com/errata/RHSA-2024:3837",
			"source": "MISC",
			"url": "https://access.redhat.com/errata/RHSA-2024:3837"
		},
		{
			"text": "https://access.redhat.com/security/cve/CVE-2024-3657",
			"source": "MISC",
			"url": "https://access.redhat.com/security/cve/CVE-2024-3657"
		}
	],
	"votes": {}
}
