{
	"name": "CVE-2019-12903",
	"seq": "2019-12903",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20190619"
	},
	"desc": "Pydio Cells before 1.5.0, when supplied with a Name field in an unexpected Unicode format, fails to handle this and includes the database column/table name as pert of the error message, exposing sensitive information.",
	"refs": [
		{
			"text": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security",
			"source": "MISC",
			"url": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-150-performances-features-security"
		},
		{
			"text": "https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/",
			"source": "MISC",
			"url": "https://research.loginsoft.com/vulnerability/multiple-vulnerabilities-in-pydio-cells-1-4-1/"
		}
	],
	"votes": {}
}
