{
	"name": "CVE-2020-24372",
	"seq": "2020-24372",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20200817"
	},
	"desc": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c.",
	"refs": [
		{
			"text": "https://github.com/LuaJIT/LuaJIT/issues/603",
			"source": "MISC",
			"url": "https://github.com/LuaJIT/LuaJIT/issues/603"
		}
	],
	"votes": {}
}
