{
  "name": "CVE-2022-1508",
  "seq": "2022-1508",
  "type": "CAN",
  "status": "Candidate",
  "phase": {
    "text": "Assigned",
    "date": "20220427"
  },
  "desc": "An out-of-bounds read flaw was found in the Linux kernelâ€™s io_uring module in the way a user triggers the io_read() function with some special parameters. This flaw allows a local user to read some memory out of bounds.",
  "refs": [
    {
      "text": "https://access.redhat.com/security/cve/CVE-2022-1508",
      "source": "MISC",
      "url": "https://access.redhat.com/security/cve/CVE-2022-1508"
    },
    {
      "text": "https://bugzilla.redhat.com/show_bug.cgi?id=2075533",
      "source": "MISC",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2075533"
    },
    {
      "text": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=89c2b3b74918200e46699338d7bcc19b1ea12110",
      "source": "MISC",
      "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=89c2b3b74918200e46699338d7bcc19b1ea12110"
    },
    {
      "text": "https://ubuntu.com/security/CVE-2022-1508",
      "source": "MISC",
      "url": "https://ubuntu.com/security/CVE-2022-1508"
    }
  ],
  "votes": {}
}
