{
  "name": "CVE-2022-42731",
  "seq": "2022-42731",
  "type": "CAN",
  "status": "Candidate",
  "phase": {
    "text": "Assigned",
    "date": "20221010"
  },
  "desc": "mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.",
  "refs": [
    {
      "text": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58",
      "source": "MISC",
      "url": "https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58"
    },
    {
      "text": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release",
      "source": "MISC",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release"
    },
    {
      "text": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release",
      "source": "MISC",
      "url": "https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release"
    }
  ],
  "votes": {}
}
