{
	"name": "CVE-2021-33010",
	"seq": "2021-33010",
	"type": "CAN",
	"status": "Candidate",
	"phase": {
		"text": "Assigned",
		"date": "20210513"
	},
	"desc": "An exception is thrown from a function in AVEVA System Platform versions 2017 through 2020 R2 P01, but it is not caught, which may cause a denial-of-service condition.",
	"refs": [
		{
			"text": "https://www.aveva.com/content/dam/aveva/documents/support/cyber-security-updates/SecurityBulletin_AVEVA-2021-002.pdf",
			"source": "CONFIRM",
			"url": "https://www.aveva.com/content/dam/aveva/documents/support/cyber-security-updates/SecurityBulletin_AVEVA-2021-002.pdf"
		},
		{
			"text": "https://www.cisa.gov/uscert/ics/advisories/icsa-21-180-05",
			"source": "CONFIRM",
			"url": "https://www.cisa.gov/uscert/ics/advisories/icsa-21-180-05"
		}
	],
	"votes": {}
}
